import {
  Youtube,
  Twitter,
  Instagram,
  Facebook,
  Linkedin,
  Music2,
  AtSign,
} from 'lucide-react';

export const platforms = [
  {
    Icon: Youtube,
    name: 'YouTube',
    color: '#FF0000',
    bg: 'from-red-500/10 to-red-500/5',
    desc: 'Import videos and repurpose them into posts for every other platform automatically.',
    users: '2.7B monthly active users',
    keyMetric: '500+ hours of video uploaded every minute',
    detail: 'YouTube is the world\'s second-largest search engine with over 2.7 billion monthly active users. It processes more than 500 hours of video uploaded every minute and drives massive organic discovery through its recommendation algorithm. For content creators and businesses, YouTube represents the foundation of any video-first strategy. Long-form content on YouTube has an average watch time that generates substantial ad revenue, with top creators earning six to seven figures annually. The platform\'s SEO capabilities mean your content can be discovered years after publishing, unlike the ephemeral nature of other social platforms. YouTube Shorts has exploded to over 70 billion daily views, competing directly with TikTok and Instagram Reels. PostPilot.Help lets you import your YouTube videos and instantly repurpose them into optimized posts for every other platform — turning one piece of content into seven or more touchpoints across your entire social presence.',
  },
  {
    Icon: Instagram,
    name: 'Instagram',
    color: '#E4405F',
    bg: 'from-pink-500/10 to-pink-500/5',
    desc: 'Plan Reels, Stories, and carousels with pixel-perfect previews before publishing.',
    users: '2B monthly active users',
    keyMetric: '67% more engagement from Reels vs static posts',
    detail: 'Instagram has over 2 billion monthly active users and remains the top platform for visual storytelling and brand building. The platform\'s algorithm heavily favors Reels, with short-form video content receiving up to 67% more engagement than static posts. Instagram Stories reach over 500 million users daily, making them essential for maintaining top-of-mind awareness with your audience. The platform has evolved far beyond photo sharing — it now supports shopping, live streaming, collaborative posts, and broadcast channels. For businesses, Instagram generates the highest ROI of any social platform for influencer marketing, with the industry valued at over $21 billion. PostPilot.Help formats your content perfectly for Instagram\'s unique requirements, including optimal caption length, hashtag placement, and Reels-friendly formatting.',
  },
  {
    Icon: Twitter,
    name: 'X / Twitter',
    color: '#1DA1F2',
    bg: 'from-sky-500/10 to-sky-500/5',
    desc: 'Schedule tweets with perfect timing and AI-generated thread ideas.',
    users: '600M monthly active users',
    keyMetric: 'Threads generate 3-5x more engagement than single tweets',
    detail: 'X (formerly Twitter) remains the epicenter of real-time conversation with approximately 600 million monthly active users. The platform is uniquely powerful for thought leadership, breaking news, and building direct relationships with your audience. Threads and long-form posts have transformed X from a micro-blogging platform into a full content publishing ecosystem. The platform\'s algorithm now favors longer, more substantive posts, with threads generating 3-5x more engagement than single tweets. For businesses and creators, X offers unmatched potential for viral reach — a single well-crafted post can reach millions organically. The advertising platform reaches over 550 million monthly users globally. PostPilot.Help generates platform-perfect posts with optimal character counts, thread structures, and engagement-driving formatting.',
  },
  {
    Icon: Facebook,
    name: 'Facebook',
    color: '#1877F2',
    bg: 'from-blue-600/10 to-blue-600/5',
    desc: 'Auto-post to Pages and Groups to keep your community engaged daily.',
    users: '3B monthly active users',
    keyMetric: '1.8B users active in Groups monthly',
    detail: 'Facebook is the world\'s largest social network with 3 billion monthly active users. Despite shifting trends, Facebook remains the most effective platform for reaching audiences over 25, particularly for local businesses, community building, and group engagement. Facebook Groups have become the platform\'s most valuable feature, with over 1.8 billion users actively participating in groups monthly. The platform\'s advertising system is the most sophisticated in the world, generating over $113 billion in annual ad revenue. For content creators, Facebook\'s monetization programs including Stars, Reels bonuses, and subscription groups create multiple income streams. PostPilot.Help helps you maintain consistent Facebook posting with community-first content that drives engagement and group participation.',
  },
  {
    Icon: Linkedin,
    name: 'LinkedIn',
    color: '#0A66C2',
    bg: 'from-blue-700/10 to-blue-700/5',
    desc: 'Grow your professional audience with polished, business-ready content.',
    users: '1B members across 200 countries',
    keyMetric: '80% of B2B leads from social media come from LinkedIn',
    detail: 'LinkedIn has over 1 billion members across 200 countries and is the undisputed platform for B2B marketing and professional content. The platform has transformed from a job board into a full content ecosystem, with newsletter subscribers growing 40% year-over-year. LinkedIn\'s algorithm currently provides the highest organic reach of any major social platform — posts regularly reach 5-10x more people than the poster\'s follower count. For businesses, LinkedIn generates 80% of B2B leads from social media and has a conversion rate 3x higher than other platforms. The creator program has attracted professionals across every industry, and thought leadership content consistently outperforms promotional posts. PostPilot.Help formats your content in LinkedIn\'s professional style, optimizing for the platform\'s preference for personal stories, industry insights, and carousel posts.',
  },
  {
    Icon: Music2,
    name: 'TikTok',
    color: '#00F2EA',
    bg: 'from-teal-400/10 to-teal-400/5',
    desc: 'Clip and share short-form video to reach the fastest-growing audience.',
    users: '1.5B monthly active users',
    keyMetric: '95 minutes average daily time spent per user',
    detail: 'TikTok has over 1.5 billion monthly active users and has fundamentally changed how content is discovered and consumed online. The platform\'s For You algorithm is the most powerful content discovery engine ever built, giving creators of any size the ability to reach millions of viewers on their very first post. TikTok users spend an average of 95 minutes per day on the platform — more than any other social network. The platform has expanded beyond dance videos into education, business, news, and long-form content up to 10 minutes. TikTok Shop has generated billions in commerce, making it a full business platform. For content creators, TikTok offers the fastest path to audience growth, with accounts regularly gaining tens of thousands of followers in weeks. PostPilot.Help helps you format short-form content optimized for TikTok\'s unique vertical video style, trending sounds, and caption requirements.',
  },
  {
    Icon: AtSign,
    name: 'Threads',
    color: '#000000',
    bg: 'from-gray-500/10 to-gray-500/5',
    desc: 'Cross-post to Threads instantly and join the conversation on Meta\'s newest platform.',
    users: '200M monthly active users',
    keyMetric: 'One of the fastest-growing platforms in history',
    detail: 'Threads by Meta launched in 2023 and has rapidly grown to over 200 million monthly active users, making it one of the fastest-growing social platforms in history. Built as a text-first companion to Instagram, Threads offers a conversational experience that combines the best of Twitter\'s real-time discussion with Instagram\'s visual community. The platform benefits from direct integration with Instagram, allowing instant audience migration and cross-posting capabilities. Threads\' algorithm favors genuine conversation and community engagement over viral content, making it ideal for building authentic connections with your audience. For businesses and creators already established on Instagram, Threads provides a natural extension to engage with followers through text-based discussions, polls, and community building. PostPilot.Help lets you cross-post to Threads simultaneously with your other platforms, maintaining a consistent presence without extra effort.',
  },
];
