/* This file is auto-generated by Convex. It will be overwritten when you run `convex dev`. */
/* eslint-disable */

// Stub types for development before Convex is initialized
export declare const api: any;
export declare const internal: any;
export declare const components: any;
