/* This file is auto-generated by Convex. It will be overwritten when you run `convex dev`. */
/* eslint-disable */

// Stub exports for development before Convex is initialized
export const api = {};
export const internal = {};
export const components = {};
