/* This file is auto-generated by Convex. It will be overwritten when you run `convex dev`. */
/* eslint-disable */

export { query, mutation, action, internalQuery, internalMutation, internalAction, httpAction } from "convex/server";
export type { DatabaseReader, DatabaseWriter } from "convex/server";
